AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      FunctionName: !Ref testfunction
      Role: arn:aws:iam::786051835021:role/Recognition-S3-Cloudwatch
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event,context):
              message = 'Hello Lambda'
              return message
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active