AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket

  # Functions
  S3TriggeredLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      Code: 
        S3Bucket: uploadbucketrecog
        S3Key: lambda_function.zip
      Handler: lambda.handler
      FunctionName: image-clog-recogusingyml
      Role: arn:aws:iam::786051835021:role/Recognition-S3-Cloudwatch
      Description: Function that is called when a file is stored in S3.
      Runtime: python3.8
      TracingConfig:
        Mode: Active
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket: image-rekog-lambdafunction
            Events: 's3:ObjectCreated:*'

  # Permissions
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: image-clog-recogusingyml
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt S3Bucket.Arn