AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      FunctionName: image-clog-recogusingyml
      Role: arn:aws:iam::786051835021:role/Recognition-S3-Cloudwatch
      Handler: index.handler
      Code: 
        S3Bucket: uploadbucketrecog
        S3Key: lambda_function.zip
          
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active